version: 2.1
jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy --template-file bucket.yml --stack-name "bkt-${CIRCLE_WORKFLOW_ID:0:7}" --parameter-overrides NAME="bkt-${CIRCLE_WORKFLOW_ID:0:7}"
      - run: aws s3 sync . s3://"bkt-${CIRCLE_WORKFLOW_ID:0:7}" --delete
    
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name cloudfront \
            --parameter-overrides PipelineID="bkt-${CIRCLE_WORKFLOW_ID:0:7}"


workflows:
  default:
    jobs:
      - create_and_deploy_front_end
      - promote_to_production:
          requires: 
            - create_and_deploy_front_end